name: TF-3.11
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow
  - keras
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - joblib
  - pip
  - pip:
      - azureml-core
      - onnx
      - azureml-inference-server-http